docker:
  base_dir: "/opt/containers"

scripts:
  base_dir: "/opt/maintenance"
  backup:
    directory: "/backup"

subdomains:
  traefik: dashboard
  traefik_metrics: metrics
  portainer: portainer
  uptimekuma: status
  etherpad: pad
  homepage: www

monitoring:
  metrics:
    url: "https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push"
    username: ""
    password: ""
  logs:
    url: "https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push"
    username: ""
    password: ""

telegram:
  chatid: 
  token: 
