- name: Create directory for Docker files
  ansible.builtin.file:
    path: "{{ docker.base_dir }}/static/"
    state: directory
    mode: "0644"

- name: Create configuration file for static homepage
  become: true
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ docker.base_dir }}/static/.env"
    mode: "0644"

- name: Copy Docker Compose file
  become: true
  ansible.builtin.copy:
    src: files/docker-compose.yml
    dest: "{{ docker.base_dir }}/static/docker-compose.yml"
    mode: "0644"

- name: Copy HTML files for static homepage
  become: true
  ansible.builtin.copy:
    src: files/html
    dest: "{{ docker.base_dir }}/static/"
    mode: "0644"

- name: Start Docker container for static homepage
  community.docker.docker_compose_v2:
    project_src: "{{ docker.base_dir }}/static"
    state: present
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
  when: false
